spring:
    application:
        name: OpenSchoolT1

    datasource:
        url: jdbc:postgresql://localhost:5432/task
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        open-in-view: false